apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-adapter
  namespace: clinicops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mcp-adapter
  template:
    metadata:
      labels:
        app: mcp-adapter
    spec:
      containers:
      - name: mcp-adapter
        image: clinicopsacr.azurecr.io/mcp-adapter:1.0
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: MCP_URL
          value: "http://mcp-orchestrator:8080/orchestrate"
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: adapter-secrets
              key: API_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: mcp-adapter
  namespace: clinicops
spec:
  selector:
    app: mcp-adapter
  ports:
  - port: 8080
=======
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-adapter
  namespace: clinicops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mcp-adapter
  template:
    metadata:
      labels:
        app: mcp-adapter
    spec:
      containers:
      - name: mcp-adapter
        image: clinicopsacr.azurecr.io/mcp-adapter:1.0
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: MCP_URL
          value: "http://mcp-orchestrator:8080/orchestrate"
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: adapter-secrets
              key: API_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: mcp-adapter
  namespace: clinicops
spec:
  selector:
    app: mcp-adapter
  ports:
  - port: 8080
>>>>>>> 36e5237e7bffa008bd28b6e3306650c9ec2bb671
    targetPort: 8080