piVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: clinicops

resources:
  - 01-mcp-orchestrator.yaml
  - 02-mcp-adapter.yaml
  - 03-voice-api.yaml
  - 04-ingress.yaml

images:
  - name: clinicopsacr.azurecr.io/voice-api
    newTag: "1.0"
  - name: clinicopsacr.azurecr.io/mcp-adapter
    newTag: "1.0"
  - name: clinicopsacr.azurecr.io/mcp-orchestrator
    newTag: "1.0"