apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: clinicops

resources:
  - voice-api-deployment.yaml
  - voice-api-service.yaml
  - mcp-adapter-deployment.yaml
  - mcp-adapter-service.yaml
  - mcp-orchestrator-deployment.yaml
  - mcp-orchestrator-service.yaml
  - ingress.yaml
